In [22]:
%cd /home/jvillarreal/

/home/jvillarreal


In [23]:
!ncdump -h /poorgafile1/climate/hdcp2/2013/3d_coarse_day_ll_DOM03_ML_20130502T120000Z.nc

netcdf \3d_coarse_day_ll_DOM03_ML_20130502T120000Z {
dimensions:
	lon = 589 ;
	lat = 637 ;
	height = 150 ;
	bnds = 2 ;
	height_2 = 151 ;
	time = UNLIMITED ; // (12 currently)
variables:
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	double lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	double height(height) ;
		height:standard_name = "height" ;
		height:long_name = "generalized_height" ;
		height:axis = "Z" ;
		height:bounds = "height_bnds" ;
	double height_bnds(height, bnds) ;
	double height_2(height_2) ;
		height_2:standard_name = "height" ;
		height_2:long_name = "generalized_height" ;
		height_2:axis = "Z" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:units = "day as %Y%m%d.%f" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
	float hus(time, height, lat, lon) ;
		hus:standard_name

In [2]:
%reload_ext autoreload
%autoreload 2

In [3]:
!cdo seltimestep,6 /poorgafile1/climate/hdcp2/2013/3d_coarse_day_ll_DOM03_ML_20130502T120000Z.nc /home/jvillarreal/3d_coarse_day_ll_DOM03_ML_20130502T120000Z_6timestep.nc

cdo    seltimestep: Processed 21 variables over 7 timesteps [9.92s 190MB].


In [45]:
!cdo -selvar,cli,clw,clc,hus,qr,qs,pres,ta  /home/jvillarreal/3d_coarse_day_ll_DOM03_ML_20130502T120000Z_6timestep.nc /home/jvillarreal/3d_coarse_day_ll_DOM03_ML_20130502T120000Z_6timestep_rttov.nc

cdo    selname: Processed 21 variables over 1 timestep [4.42s 5711MB].


In [58]:
!ncwa -a time /home/jvillarreal/3d_coarse_day_ll_DOM03_ML_20130502T120000Z_6timestep_rttov.nc /home/jvillarreal/3D.nc

In [59]:
!ncdump -h /home/jvillarreal/3D.nc

netcdf \3D {
dimensions:
	lon = 589 ;
	lat = 637 ;
	height = 150 ;
	bnds = 2 ;
variables:
	double time ;
		time:standard_name = "time" ;
		time:units = "day as %Y%m%d.%f" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
		time:cell_methods = "time: mean" ;
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	double lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	double height(height) ;
		height:standard_name = "height" ;
		height:long_name = "generalized_height" ;
		height:axis = "Z" ;
		height:bounds = "height_bnds" ;
	double height_bnds(height, bnds) ;
	float hus(height, lat, lon) ;
		hus:standard_name = "specific_humidity" ;
		hus:long_name = "Specific humidity" ;
		hus:units = "kg kg-1" ;
		hus:param = "0.1.0" ;
		hus:cell_methods = "time: mean" ;
	float clw(height, lat, lon) ;
		clw:standard_name = "qc"

### Check copied 3D data 

In [60]:
import os
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

fname_3D = '/poorgafile1/climate/hdcp2/2013/3d_coarse_day_ll_DOM03_ML_20130502T120000Z.nc'
fname_3D_6timestep = '/home/jvillarreal/3D.nc'

In [61]:
ds_3D = xr.open_dataset(fname_3D)
print('---------ds_3D--------------')
ds_3D

---------ds_3D--------------


<xarray.Dataset>
Dimensions:      (bnds: 2, height: 150, height_2: 151, lat: 637, lon: 589, time: 12)
Coordinates:
  * lon          (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
  * lat          (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * height       (height) float64 1.0 2.0 3.0 4.0 ... 147.0 148.0 149.0 150.0
  * height_2     (height_2) float64 1.0 2.0 3.0 4.0 ... 148.0 149.0 150.0 151.0
  * time         (time) float64 2.013e+07 2.013e+07 ... 2.013e+07 2.013e+07
Dimensions without coordinates: bnds
Data variables:
    height_bnds  (height, bnds) float64 ...
    hus          (time, height, lat, lon) float32 ...
    clw          (time, height, lat, lon) float32 ...
    cli          (time, height, lat, lon) float32 ...
    qr           (time, height, lat, lon) float32 ...
    qs           (time, height, lat, lon) float32 ...
    qg           (time, height, lat, lon) float32 ...
    qh           (time, height, lat, lon) float32 ...
    qnc          (time, height, lat, lon) float32 ...
    qni          (time, height, lat, lon) float32 ...
    qnr          (time, height, lat, lon) float32 ...
    qns          (time, height, lat, lon) float32 ...
    qng          (time, height, lat, lon) float32 ...
    qnh          (time, height, lat, lon) float32 ...
    ninact       (time, height, lat, lon) float32 ...
    ua           (time, height, lat, lon) float32 ...
    va           (time, height, lat, lon) float32 ...
    wa           (time, height_2, lat, lon) float32 ...
    ta           (time, height, lat, lon) float32 ...
    pres         (time, height, lat, lon) float32 ...
    tkvh         (time, height_2, lat, lon) float32 ...
    clc          (time, height, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data Interface version 1.7.2 (http://mpimet.mpg.de/...
    Conventions:  CF-1.4
    uuidOfVGrid:  3be5ac35-92f4-4e91-7418-b62336222e20
    institution:  Max Planck Institute for Meteorology/Deutscher Wetterdienst
    title:        ICON simulation
    source:       git@git.mpimet.mpg.de:icon-lem.git@a67e3681e4833c13bb195f60...
    history:      /work/bm0834/k203095/icon-lem-alpha/icon-lem-readccn/build/...
    references:   see MPIM/DWD publications
    comment:      HDCP2 Sammelaccount (k203095) on m21726 (Linux 2.6.32-696.1...

In [64]:
ds_3D_6 = xr.open_dataset(fname_3D_6timestep)
print('---------ds_3D_6--------------')
ds_3D_6

---------ds_3D_6--------------


<xarray.Dataset>
Dimensions:      (bnds: 2, height: 150, lat: 637, lon: 589)
Coordinates:
  * lon          (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
  * lat          (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * height       (height) float64 1.0 2.0 3.0 4.0 ... 147.0 148.0 149.0 150.0
Dimensions without coordinates: bnds
Data variables:
    time         float64 ...
    height_bnds  (height, bnds) float64 ...
    hus          (height, lat, lon) float32 ...
    clw          (height, lat, lon) float32 ...
    cli          (height, lat, lon) float32 ...
    qr           (height, lat, lon) float32 ...
    qs           (height, lat, lon) float32 ...
    ta           (height, lat, lon) float32 ...
    pres         (height, lat, lon) float32 ...
    clc          (height, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data Interface version 1.9.7.1 (http://mpimet.mpg.d...
    history:      Mon Apr 26 11:21:37 2021: ncwa -a time /home/jvillarreal/3d...
    uuidOfVGrid:  3be5ac35-92f4-4e91-7418-b62336222e20
    source:       git@git.mpimet.mpg.de:icon-lem.git@a67e3681e4833c13bb195f60...
    institution:  Max Planck Institute for Meteorology
    Conventions:  CF-1.4
    title:        ICON simulation
    references:   see MPIM/DWD publications
    comment:      HDCP2 Sammelaccount (k203095) on m21726 (Linux 2.6.32-696.1...
    CDO:          Climate Data Operators version 1.9.7.1 (http://mpimet.mpg.d...
    NCO:          netCDF Operators version 4.8.1 (Homepage = http://nco.sf.ne...

In [85]:
hus_o =ds_3D['hus']
print('-----------------------')
print('hus,data_original shape',hus_o.shape,hus_o.values[5,:,:,:].shape)

hus =ds_3D_6['hus']
print('-----------------------')
print('hus,data_copied shape',hus.shape,hus.values[:,:,:].shape)

np.array_equal(hus_o.values[5,:,:,:],hus.values[:,:,:])

-----------------------
hus,data_original shape (12, 150, 637, 589) (150, 637, 589)
-----------------------
hus,data_copied shape (150, 637, 589) (150, 637, 589)


True

In [ ]:
##3 hay otra forma de hacer esto usando cdo xq tengo q seleccionar un time step

In [83]:
for v in ds_3D_6.data_vars:
    if (v != ('time') and v !=('height_bnds')):
        print(v,':copied correctly')
        np.array_equal(ds_3D[v].values[5,:,:,:],ds_3D_6[v].values[:,:,:])

hus :copied correctly
clw :copied correctly
cli :copied correctly
qr :copied correctly
qs :copied correctly
ta :copied correctly
pres :copied correctly
clc :copied correctly


# 2D

In [90]:
!ncdump -h /poorgafile1/climate/hdcp2/2013/2d_surface_day_DOM03_ML_20130502T120000Z.nc 

netcdf \2d_surface_day_DOM03_ML_20130502T120000Z {
dimensions:
	height = 1 ;
	time = UNLIMITED ; // (60 currently)
	ncells = 22282304 ;
variables:
	double height(height) ;
		height:standard_name = "height" ;
		height:long_name = "height" ;
		height:units = "m" ;
		height:positive = "up" ;
		height:axis = "Z" ;
	float lhfl_s(time, ncells) ;
		lhfl_s:standard_name = "lhfl_s" ;
		lhfl_s:long_name = "surface latent heat flux" ;
		lhfl_s:units = "W m-2" ;
		lhfl_s:param = "10.0.0" ;
		lhfl_s:grid_type = "unstructured" ;
		lhfl_s:number_of_grid_in_reference = 1 ;
	float ps(time, ncells) ;
		ps:standard_name = "surface_air_pressure" ;
		ps:long_name = "surface pressure" ;
		ps:units = "Pa" ;
		ps:param = "0.3.0" ;
		ps:grid_type = "unstructured" ;
		ps:number_of_grid_in_reference = 1 ;
	float shfl_s(time, ncells) ;
		shfl_s:standard_name = "shfl_s" ;
		shfl_s:long_name = "surface sensible heat flux" ;
		shfl_s:units = "W m-2" ;
		shfl_s:param = "11.0.0" ;
		shfl_s:grid_type = "unstructured" ;

In [ ]:
!cdo seltimestep,6 /poorgafile1/climate/hdcp2/2013/3d_coarse_day_ll_DOM03_ML_20130502T120000Z.nc /home/jvillarreal/3d_coarse_day_ll_DOM03_ML_20130502T120000Z_6timestep.nc

In [27]:
ds_3D_c=ds_3D.values[5,:,:,:]
ds_3D_6_c=ds_3D_6.values[0,:,:]



TypeError: 'method' object is not subscriptable

In [14]:
print('Values:min, max')
print(height.min().values,height.max().values)


Values:min, max
146.78531 20808.896


In [15]:
print('Values:min, max')
print(height_half.min().values,height_half.max().values)

Values:min, max
136.78531 20617.793


In [16]:
# height_half =ds['z_ifc']
height[:,1,1].values

array([  351.52188,   375.4153 ,   405.9043 ,   440.8925 ,   479.15475,
         520.1691 ,   563.594  ,   609.1865 ,   656.76465,   706.18695,
         757.3403 ,   810.1323 ,   864.4866 ,   920.3387 ,   977.63416,
        1036.3262 ,  1096.3745 ,  1157.744  ,  1220.4044 ,  1284.3289 ,
        1349.494  ,  1415.8794 ,  1483.4667 ,  1552.24   ,  1622.185  ,
        1693.2896 ,  1765.5425 ,  1838.9341 ,  1913.4558 ,  1989.1002 ,
        2065.8608 ,  2143.732  ,  2222.7087 ,  2302.7869 ,  2383.963  ,
        2466.2336 ,  2549.597  ,  2634.0508 ,  2719.5933 ,  2806.2236 ,
        2893.9412 ,  2982.7454 ,  3072.636  ,  3163.6138 ,  3255.6787 ,
        3348.8318 ,  3443.0742 ,  3538.407  ,  3634.8318 ,  3732.3503 ,
        3830.9644 ,  3930.676  ,  4031.4875 ,  4133.4014 ,  4236.4204 ,
        4340.547  ,  4445.784  ,  4552.1353 ,  4659.6035 ,  4768.1924 ,
        4877.9053 ,  4988.746  ,  5100.7183 ,  5213.8267 ,  5328.075  ,
        5443.4683 ,  5560.0103 ,  5677.7065 ,  5796.561  ,  5916

In [20]:
height_half[:,5,2].values

array([  318.4248 ,   338.4248 ,   366.30908,   399.58676,   436.4771 ,
         476.33743,   518.76263,   563.47174,   610.2579 ,   658.9621 ,
         709.45874,   761.646  ,   815.4398 ,   870.76996,   927.57715,
         985.8105 ,  1045.4264 ,  1106.3871 ,  1168.6595 ,  1232.2148 ,
        1297.0278 ,  1363.0763 ,  1430.3403 ,  1498.8029 ,  1568.4482 ,
        1639.2632 ,  1711.2354 ,  1784.3544 ,  1858.6107 ,  1933.9961 ,
        2010.5032 ,  2088.1257 ,  2166.858  ,  2246.695  ,  2327.633  ,
        2409.6685 ,  2492.7979 ,  2577.019  ,  2662.3298 ,  2748.729  ,
        2836.2148 ,  2924.787  ,  3014.4448 ,  3105.1882 ,  3197.017  ,
        3289.9324 ,  3383.934  ,  3479.0237 ,  3575.2021 ,  3672.471  ,
        3770.8313 ,  3870.2856 ,  3970.8354 ,  4072.4832 ,  4175.231  ,
        4279.0815 ,  4384.0376 ,  4490.102  ,  4597.2783 ,  4705.569  ,
        4814.977  ,  4925.5073 ,  5037.163  ,  5149.9478 ,  5263.8657 ,
        5378.9214 ,  5495.119  ,  5612.4634 ,  5730.9595 ,  5850

### My data

In [14]:
import os
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
fname = '/home/jvillarreal/GRID_DOM3.nc'
ds = xr.open_dataset(fname)

In [15]:
!ncdump -h /home/jvillarreal/GRID_DOM3.nc 

netcdf GRID_DOM3 {
dimensions:
	lon = 589 ;
	lat = 637 ;
	height = 151 ;
	bnds = 2 ;
	height_2 = 150 ;
variables:
	double lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	double lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	double height(height) ;
		height:standard_name = "height" ;
		height:long_name = "generalized height" ;
		height:axis = "Z" ;
		height:bounds = "height_bnds" ;
	double height_bnds(height, bnds) ;
	double height_2(height_2) ;
		height_2:standard_name = "height" ;
		height_2:long_name = "generalized height" ;
		height_2:axis = "Z" ;
		height_2:bounds = "height_2_bnds" ;
	double height_2_bnds(height_2, bnds) ;
	float z_ifc(height, lat, lon) ;
		z_ifc:standard_name = "geometric_height_at_half_level_center" ;
		z_ifc:long_name = "geometric height at half level center" ;
		z_ifc:units = "m" ;
		z_ifc:param = "6

### start create my new data

In [24]:


from netCDF4 import Dataset    # Note: python is case-sensitive!
import numpy as np

try: ncfile.close()  # just to be safe, make sure dataset is not already open.
except: pass
ncfile = Dataset('/home/jvillarreal/GRID_DOM3_new.nc',mode='w',format='NETCDF4') 
print(ncfile)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    dimensions(sizes): 
    variables(dimensions): 
    groups: 


In [25]:
lat_dim = ncfile.createDimension('lat', 637)     # latitude axis
lon_dim = ncfile.createDimension('lon', 589)    # longitude axis
height_dim = ncfile.createDimension('height', 150) # unlimited axis (can be appended to).
bnds_dim = ncfile.createDimension('bnds', 2)
for dim in ncfile.dimensions.items():
    print(dim)

('lat', <class 'netCDF4._netCDF4.Dimension'>: name = 'lat', size = 637)
('lon', <class 'netCDF4._netCDF4.Dimension'>: name = 'lon', size = 589)
('height', <class 'netCDF4._netCDF4.Dimension'>: name = 'height', size = 150)
('bnds', <class 'netCDF4._netCDF4.Dimension'>: name = 'bnds', size = 2)


In [26]:
ncfile.title='Modify zifc and zmc'
print(ncfile.title)

Modify zifc and zmc


<ipython-input-26-c18419099fa6>:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(ncfile.title)


In [27]:
lat = ncfile.createVariable('lat', np.float64, ('lat',))
lat.units = 'degrees_north'
lat.standard_name = "latitude"
lat.long_name = 'latitude'
lat.axis = "Y" 

lon = ncfile.createVariable('lon', np.float64, ('lon',))
lon.units = 'degrees_east'
lon.standard_name = "longitude" 
lon.long_name = 'longitude'
lon.axis = "X"

height = ncfile.createVariable('height', np.float64, ('height'))
height.standard_name = "height"
height.long_name = 'generalized_height'
height.axis = "Z" ;
height.bounds = "height_bnds" ;


height_bnds = ncfile.createVariable('height_bnds', np.float64, ('height','bnds'))

            
Z_ifc= ncfile.createVariable('Z_ifc',np.float32,('height','lat','lon'))
Z_ifc.units = 'm' 
Z_mc= ncfile.createVariable('Z_mc',np.float32,('height','lat','lon'))
Z_mc.units = 'm' 

Topography_c=ncfile.createVariable('Topography_c',np.float32,('lat','lon'))

Z_ifc.standard_name = "geometric_height_at_half_level_center" ;
Z_ifc.long_name = "geometric height at half level center" ;
Z_ifc.units = "m" ;
Z_ifc.param = "6.3.0" ;

Z_mc.standard_name = "geometric_height_at_full_level_center" ;
Z_mc.long_name = "geometric height at full level center" ;
Z_mc.units = "m" ;
Z_mc.param = "6.3.0" ;

Topography_c.standard_name = "surface_height" ;
Topography_c.long_name = "geometric height of the earths surface above sea level" ;
Topography_c.units = "m" ;
Topography_c.param = "6.3.0" ;

In [28]:
lat[:]=ds.lat
lon[:]=ds.lon
height[:]=ds.height_2
bnds=ds.bnds

In [29]:
Z_ifc[:,:,:]=ds['z_ifc'][1:,:,:]
Z_mc[:,:,:]=ds['z_mc']
Topography_c[:,:]=ds['topography_c']

In [30]:
print("-- Min/Max values:", height[:].min(), height[:].max())

-- Min/Max values: 1.0 150.0


In [31]:
print("-- Min/Max values:", Z_ifc[:].min(), Z_ifc[:].max())

-- Min/Max values: -137.1074 20617.793


In [32]:
print("-- Min/Max values:", Z_mc[:].min(), Z_mc[:].max())

-- Min/Max values: -126.968605 20808.896


In [33]:
print(ncfile)
# close the Dataset.
ncfile.close(); print('Dataset is closed!')

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    title: Modify zifc and zmc
    dimensions(sizes): lat(637), lon(589), height(150), bnds(2)
    variables(dimensions): float64 lat(lat), float64 lon(lon), float64 height(height), float64 height_bnds(height,bnds), float32 Z_ifc(height,lat,lon), float32 Z_mc(height,lat,lon), float32 Topography_c(lat,lon)
    groups: 
Dataset is closed!


<ipython-input-33-f8f15c2181fc>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  print(ncfile)


In [34]:
!ncdump -h /home/jvillarreal/GRID_DOM3_new.nc

netcdf GRID_DOM3_new {
dimensions:
	lat = 637 ;
	lon = 589 ;
	height = 150 ;
	bnds = 2 ;
variables:
	double lat(lat) ;
		lat:units = "degrees_north" ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:axis = "Y" ;
	double lon(lon) ;
		lon:units = "degrees_east" ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:axis = "X" ;
	double height(height) ;
		height:standard_name = "height" ;
		height:long_name = "generalized_height" ;
		height:axis = "Z" ;
		height:bounds = "height_bnds" ;
	double height_bnds(height, bnds) ;
	float Z_ifc(height, lat, lon) ;
		Z_ifc:units = "m" ;
		Z_ifc:standard_name = "geometric_height_at_half_level_center" ;
		Z_ifc:long_name = "geometric height at half level center" ;
		Z_ifc:param = "6.3.0" ;
	float Z_mc(height, lat, lon) ;
		Z_mc:units = "m" ;
		Z_mc:standard_name = "geometric_height_at_full_level_center" ;
		Z_mc:long_name = "geometric height at full level center" ;
		Z_mc:param = "6.3.0" ;
	float Topography

ds

In [95]:
np.dtype(ds.height),np.dtype(ds.bnds)

(dtype('float64'), dtype('int64'))

In [2]:
ds

<xarray.Dataset>
Dimensions:        (bnds: 2, height: 151, height_2: 150, lat: 637, lon: 589)
Coordinates:
  * lon            (lon) float64 4.5 4.517 4.534 4.551 ... 14.46 14.48 14.5
  * lat            (lat) float64 47.5 47.51 47.52 47.53 ... 54.47 54.48 54.5
  * height         (height) float64 1.0 2.0 3.0 4.0 ... 148.0 149.0 150.0 151.0
  * height_2       (height_2) float64 1.0 2.0 3.0 4.0 ... 148.0 149.0 150.0
Dimensions without coordinates: bnds
Data variables:
    height_bnds    (height, bnds) float64 ...
    height_2_bnds  (height_2, bnds) float64 ...
    z_ifc          (height, lat, lon) float32 ...
    z_mc           (height_2, lat, lon) float32 ...
    topography_c   (lat, lon) float32 ...
Attributes:
    CDI:                       Climate Data Interface version 1.9.7.1 (http:/...
    history:                   Tue Apr 20 14:03:15 2021: cdo -P 8 remapnn,myG...
    source:                    @
    institution:               Max Planck Institute for Meteorology
    Conventions:               CF-1.4
    title:                     ICON simulation
    references:                see MPIM/DWD publications
    comment:                   HDCP2 Sammelaccount (k203095) on m11511 (Linux...
    CDO:                       Climate Data Operators version 1.9.7.1 (http:/...
    cdo_openmp_thread_number:  8

In [7]:
height =ds['z_mc']
print('-----------------------')
print(height)

height_half =ds['z_ifc']
print('-----------------------')
print(height_half)

-----------------------
<xarray.DataArray 'z_mc' (height_2: 150, lat: 637, lon: 589)>
[56278950 values with dtype=float32]
Coordinates:
  * lon       (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
  * lat       (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * height_2  (height_2) float64 1.0 2.0 3.0 4.0 5.0 ... 147.0 148.0 149.0 150.0
Attributes:
    standard_name:  geometric_height_at_full_level_center
    long_name:      geometric height at full level center
    units:          m
    param:          6.3.0
-----------------------
<xarray.DataArray 'z_ifc' (height: 151, lat: 637, lon: 589)>
[56654143 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
  * lat      (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * height   (height) float64 1.0 2.0 3.0 4.0 5.0 ... 148.0 149.0 150.0 151.0
Attributes:
    standard_name:  geometric_height_at_half_level_center
    long_name:  

In [8]:
print('Values:min, max')
print(height.min().values,height.max().values)

Values:min, max
-126.968605 20808.896


In [10]:
# height_half =ds['z_ifc']
height_half[:,1,1].values

array([21000.     , 20617.793  , 20290.234  , 19982.348  , 19687.436  ,
       19402.393  , 19125.412  , 18855.303  , 18591.217  , 18332.527  ,
       18078.736  , 17829.453  , 17584.35   , 17343.154  , 17105.635  ,
       16871.594  , 16640.854  , 16413.26   , 16188.679  , 15969.077  ,
       15750.355  , 15534.323  , 15320.892  , 15109.975  , 14901.498  ,
       14695.39   , 14491.585  , 14290.023  , 14090.647  , 13893.404  ,
       13698.245  , 13505.122  , 13313.994  , 13124.817  , 12937.554  ,
       12752.167  , 12568.623  , 12386.887  , 12206.93   , 12028.72   ,
       11852.2295 , 11677.433  , 11504.303  , 11332.816  , 11162.95   ,
       10994.681  , 10827.987  , 10662.851  , 10499.25   , 10337.167  ,
       10176.584  , 10017.483  ,  9859.851  ,  9703.668  ,  9548.921  ,
        9395.595  ,  9243.677  ,  9093.152  ,  8944.009  ,  8796.234  ,
        8649.816  ,  8504.745  ,  8361.008  ,  8218.594  ,  8077.4946 ,
        7937.699  ,  7799.1987 ,  7661.9834 ,  7526.045  ,  7391

In [11]:
# height_half =ds['z_ifc']
height[:,1,1].values

array([20808.896  , 20454.014  , 20136.291  , 19834.89   , 19544.914  ,
       19263.902  , 18990.357  , 18723.26   , 18461.871  , 18205.63   ,
       17954.094  , 17706.9    , 17463.752  , 17224.395  , 16988.615  ,
       16756.223  , 16527.057  , 16300.97   , 16078.878  , 15859.717  ,
       15642.34   , 15427.607  , 15215.433  , 15005.736  , 14798.443  ,
       14593.487  , 14390.804  , 14190.335  , 13992.025  , 13795.824  ,
       13601.684  , 13409.559  , 13219.405  , 13031.186  , 12844.86   ,
       12660.395  , 12477.755  , 12296.908  , 12117.824  , 11940.475  ,
       11764.831  , 11590.868  , 11418.56   , 11247.884  , 11078.815  ,
       10911.334  , 10745.419  , 10581.05   , 10418.208  , 10256.875  ,
       10097.034  ,  9938.667  ,  9781.759  ,  9626.294  ,  9472.258  ,
        9319.636  ,  9168.414  ,  9018.58   ,  8870.121  ,  8723.025  ,
        8577.281  ,  8432.876  ,  8289.801  ,  8148.0444 ,  8007.597  ,
        7868.4487 ,  7730.591  ,  7594.014  ,  7458.71   ,  7324

In [9]:
print('Values:min, max')
print(height_half.min().values,height_half.max().values)

Values:min, max
-137.1074 21000.0


### cutted GRID_DOM3

In [39]:
import os
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
fname = '/home/jvillarreal/GRID_DOM3_cut.nc'
ds = xr.open_dataset(fname)

In [40]:
ds

<xarray.Dataset>
Dimensions:        (bnds: 2, height: 150, height_2: 150, lat: 637, lon: 589)
Coordinates:
  * height         (height) float64 2.0 3.0 4.0 5.0 ... 148.0 149.0 150.0 151.0
  * height_2       (height_2) float64 1.0 2.0 3.0 4.0 ... 148.0 149.0 150.0
  * lat            (lat) float64 47.5 47.51 47.52 47.53 ... 54.47 54.48 54.5
  * lon            (lon) float64 4.5 4.517 4.534 4.551 ... 14.46 14.48 14.5
Dimensions without coordinates: bnds
Data variables:
    height_2_bnds  (height_2, bnds) float64 ...
    height_bnds    (height, bnds) float64 ...
    topography_c   (lat, lon) float32 ...
    z_ifc          (height, lat, lon) float32 ...
    z_mc           (height_2, lat, lon) float32 ...
Attributes:
    CDI:                       Climate Data Interface version 1.9.7.1 (http:/...
    history:                   Tue Apr 20 15:20:55 2021: ncks -d height,2.,15...
    source:                    @
    institution:               Max Planck Institute for Meteorology
    Conventions:               CF-1.4
    title:                     ICON simulation
    references:                see MPIM/DWD publications
    comment:                   HDCP2 Sammelaccount (k203095) on m11511 (Linux...
    CDO:                       Climate Data Operators version 1.9.7.1 (http:/...
    cdo_openmp_thread_number:  8
    NCO:                       netCDF Operators version 4.8.1 (Homepage = htt...

In [41]:
height =ds['z_mc']
print('-----------------------')
print(height)

height_half =ds['z_ifc']
print('-----------------------')
print(height_half)

-----------------------
<xarray.DataArray 'z_mc' (height_2: 150, lat: 637, lon: 589)>
[56278950 values with dtype=float32]
Coordinates:
  * height_2  (height_2) float64 1.0 2.0 3.0 4.0 5.0 ... 147.0 148.0 149.0 150.0
  * lat       (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * lon       (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
Attributes:
    standard_name:  geometric_height_at_full_level_center
    long_name:      geometric height at full level center
    units:          m
    param:          6.3.0
-----------------------
<xarray.DataArray 'z_ifc' (height: 150, lat: 637, lon: 589)>
[56278950 values with dtype=float32]
Coordinates:
  * height   (height) float64 2.0 3.0 4.0 5.0 6.0 ... 148.0 149.0 150.0 151.0
  * lat      (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * lon      (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
Attributes:
    standard_name:  geometric_height_at_half_level_center
    long_name:  

In [42]:
print('Values:min, max')
print(height.min().values,height.max().values)


Values:min, max
-126.968605 20808.896


In [43]:
print('Values:min, max')
print(height_half.min().values,height_half.max().values)

Values:min, max
-137.1074 20617.793


In [44]:
height_half

<xarray.DataArray 'z_ifc' (height: 150, lat: 637, lon: 589)>
array([[[2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        ...,
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04]],

       [[2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        ...,
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04]],

       ...,

       [[4.312412e+02, 4.316842e+02, ..., 8.808951e+02, 8.808951e+02],
        [4.312412e+02, 4.316842e+02, ..., 8.808951e+02, 8.808951e+02],
        ...,
        [2.000000e+01, 2.000000e+01, ..., 2.000000e+01, 2.000000e+01],
        [2.000000e+01, 2.000000e+01, ..., 2.000000e+01, 2.000000e+01]],

       [[4.112412e+02, 4.116842e+02, ..., 8.608951e+02, 8.608951e+02],
        [4.112412e+02, 4.116842e+02, ..., 8.608951e+02, 8.608951e+02],
        ...,
        [0.000000e+00, 0.000000e+00, ..., 0.000000e+00, 0.000000e+00],
        [0.000000e+00, 0.000000e+00, ..., 0.000000e+00, 0.000000e+00]]],
      dtype=float32)
Coordinates:
  * height   (height) float64 2.0 3.0 4.0 5.0 6.0 ... 148.0 149.0 150.0 151.0
  * lat      (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * lon      (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
Attributes:
    standard_name:  geometric_height_at_half_level_center
    long_name:      geometric height at half level center
    units:          m
    param:          6.3.0

In [45]:
height_half =ds['z_ifc']
print('-----------------------')
print(height_half)

-----------------------
<xarray.DataArray 'z_ifc' (height: 150, lat: 637, lon: 589)>
array([[[2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        ...,
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04]],

       [[2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        ...,
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04]],

       ...,

       [[4.312412e+02, 4.316842e+02, ..., 8.808951e+02, 8.808951e+02],
        [4.312412e+02, 4.316842e+02, ..., 8.808951e+02, 8.808951e+02],
        ...,
        [2.000000e+01, 2.000000e+01, ..., 2.000000e+01, 2.000000e+01],
        [2.000000e+01, 2.000000e+01, ..., 2.000000e+01, 2.000000e+01]],

     

In [46]:
ds['height']=ds['height'] -1
ds['height']

<xarray.DataArray 'height' (height: 150)>
array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
        25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
        37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
        49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
        61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
        73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
        85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
        97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
       109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
       121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
       145., 146., 147., 148., 149., 150.])
Coordinates:
  * height   (height) float64 1.0 2.0 3.0 4.0 5.0 ... 147.0 148.0 149.0 150.0

In [48]:
height_half =ds['z_ifc']
height_half

<xarray.DataArray 'z_ifc' (height: 150, lat: 637, lon: 589)>
array([[[2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        ...,
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04],
        [2.061779e+04, 2.061779e+04, ..., 2.061779e+04, 2.061779e+04]],

       [[2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        ...,
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04],
        [2.029023e+04, 2.029023e+04, ..., 2.029023e+04, 2.029023e+04]],

       ...,

       [[4.312412e+02, 4.316842e+02, ..., 8.808951e+02, 8.808951e+02],
        [4.312412e+02, 4.316842e+02, ..., 8.808951e+02, 8.808951e+02],
        ...,
        [2.000000e+01, 2.000000e+01, ..., 2.000000e+01, 2.000000e+01],
        [2.000000e+01, 2.000000e+01, ..., 2.000000e+01, 2.000000e+01]],

       [[4.112412e+02, 4.116842e+02, ..., 8.608951e+02, 8.608951e+02],
        [4.112412e+02, 4.116842e+02, ..., 8.608951e+02, 8.608951e+02],
        ...,
        [0.000000e+00, 0.000000e+00, ..., 0.000000e+00, 0.000000e+00],
        [0.000000e+00, 0.000000e+00, ..., 0.000000e+00, 0.000000e+00]]],
      dtype=float32)
Coordinates:
  * height   (height) float64 1.0 2.0 3.0 4.0 5.0 ... 147.0 148.0 149.0 150.0
  * lat      (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * lon      (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
Attributes:
    standard_name:  geometric_height_at_half_level_center
    long_name:      geometric height at half level center
    units:          m
    param:          6.3.0

In [49]:
ds.assign(z_ifc_mod=x["z_ifc_mod"] * 9 / 5 + 32)


AttributeError: 'Dataset' object has no attribute 'createVariable'

In [30]:
# read file
#file_in = 'Ocean.nc'
#nc1 = xr.open_dataset(file_in) ds
# modify a variable, e.g.:
ds.z_ifc = ds.z_ifc + 2
# save to a new netcdf file
file_out = '/home/jvillarreal/GRID_DOM3_cut_modify.nc'
nc1.to_netcdf(file_out)


FileNotFoundError: [Errno 2] No such file or directory: b'/home/jvillarreal/test_data_analysis/Ocean.nc'