In [3]:
%cd

/home/jvillarreal
/home/jvillarreal


In [ ]:
import os
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

In [4]:
!ncdump -h test-2.nc

netcdf test-2 {
dimensions:
	hydro = 9 ;
	level = 150 ;
	lat = 91 ;
	lon = 59 ;
	bnds = 2 ;
variables:
	float Reff(hydro, level, lat, lon) ;
	float T_abs(level, lat, lon) ;
	float cca(level, lat, lon) ;
	float dem_c(level, lat, lon) ;
	float dem_s(level, lat, lon) ;
	float dtau_c(level, lat, lon) ;
	float dtau_s(level, lat, lon) ;
	float emsfc_lw ;
	float fl_ccrain(level, lat, lon) ;
	float fl_ccsnow(level, lat, lon) ;
	float fl_lsgrpl(level, lat, lon) ;
	float fl_lsrain(level, lat, lon) ;
	float fl_lssnow(level, lat, lon) ;
	float height(level, lat, lon) ;
	float height_half(level, lat, lon) ;
	float iwp(lat, lon) ;
		iwp:units = "kg.m-2" ;
	float landmask(lat, lon) ;
	double lat(lat) ;
		lat:long_name = "lat" ;
	float lat_bnds(lat, bnds) ;
	double lon(lon) ;
		lon:long_name = "lon" ;
	float lon_bnds(lon, bnds) ;
	float lwp(lat, lon) ;
		lwp:units = "kg.m-2" ;
	float mr_ccice(level, lat, lon) ;
	float mr_ccliq(level, lat, lon) ;
	float mr_lsice(level, lat, lon) ;
	float mr_lsliq(level

In [5]:
!ncdump -h test-rttov.nc

netcdf test-rttov {
dimensions:
	lat = 91 ;
	lon = 59 ;
	height = 150 ;
	bnds = 2 ;
variables:
	int cell_sea_land_mask(lat, lon) ;
		cell_sea_land_mask:long_name = "sea (-2 inner, -1 boundary) land (2 inner, 1 boundary) mask for the cell" ;
		cell_sea_land_mask:units = "2,1,-1,-" ;
	float clc(height, lat, lon) ;
		clc:standard_name = "clc" ;
		clc:long_name = "cloud cover" ;
		clc:units = "%" ;
		clc:param = "22.6.0" ;
		clc:cell_methods = "time: mean" ;
	float cli(height, lat, lon) ;
		cli:standard_name = "qi" ;
		cli:long_name = "specific_cloud_ice_content" ;
		cli:units = "kg kg-1" ;
		cli:param = "82.1.0" ;
		cli:cell_methods = "time: mean" ;
	float clw(height, lat, lon) ;
		clw:standard_name = "qc" ;
		clw:long_name = "specific_cloud_water_content" ;
		clw:units = "kg kg-1" ;
		clw:param = "22.1.0" ;
		clw:cell_methods = "time: mean" ;
	double height(height) ;
		height:standard_name = "height" ;
		height:long_name = "generalized_height" ;
		height:axis = "Z" ;
		height:bounds = "h

In [45]:
import os
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
fname_test = '/home/jvillarreal/test.nc'
fname_mydata = '/home/jvillarreal/input_test_rttov.nc'

ds_test = xr.open_dataset(fname_test)
ds_mydata = xr.open_dataset(fname_mydata)


In [46]:
print('------------------------------------------------------')
print()
print('--> print example min')
print()
print(ds_test.min().values)
print()
print('--> print example max')
print()
print(ds_test.max().values)
print()

------------------------------------------------------

--> print example min

<bound method Mapping.values of <xarray.Dataset>
Dimensions:      ()
Data variables:
    lat_bnds     float32 0.0
    lon_bnds     float32 0.0
    height       float32 -132.4
    pfull        float32 0.0
    phalf        float32 0.0
    T_abs        float32 0.0
    qv           float32 0.0
    rh           float32 0.0
    tca          float32 0.0
    cca          float32 0.0
    mr_lsliq     float32 0.0
    mr_lsice     float32 0.0
    mr_ccliq     float32 0.0
    mr_ccice     float32 0.0
    fl_lsrain    float32 0.0
    fl_lssnow    float32 0.0
    fl_lsgrpl    float32 0.0
    fl_ccrain    float32 0.0
    fl_ccsnow    float32 0.0
    orography    float32 -142.5
    landmask     float32 0.0
    height_half  float32 0.0
    psfc         float32 7.711e+04
    Reff         float32 0.0
    dtau_s       float32 0.0
    dtau_c       float32 0.0
    dem_s        float32 0.0
    dem_c        float32 0.0
    skt     

In [47]:
print('------------------------My dataset------------------------------')
print()
print('--> print my data min')
print()
print(ds_mydata.min().values)
print()
print('--> print my data max')
print()
print(ds_mydata.max().values)
print()

------------------------My dataset------------------------------

--> print my data min

<bound method Mapping.values of <xarray.Dataset>
Dimensions:       ()
Data variables:
    height_bnds   float64 1.0
    hus           float32 0.0
    clw           float32 0.0
    cli           float32 0.0
    qr            float32 0.0
    qs            float32 0.0
    ta            float32 0.0
    pres          float32 0.0
    clc           float32 0.0
    ps            float32 7.725e+04
    u_10m         float32 -9.355
    v_10m         float32 -9.19
    t_s           float32 275.6
    FR_LAND       float32 0.0
    Z_ifc         float32 -137.1
    Z_mc          float32 -127.0
    Topography_c  float32 -137.1>

--> print my data max

<bound method Mapping.values of <xarray.Dataset>
Dimensions:       ()
Data variables:
    height_bnds   float64 151.0
    hus           float32 0.01027
    clw           float32 0.001286
    cli           float32 0.0002771
    qr            float32 0.001893
    qs    

In [48]:
print('---------ds_test--------------')
ds_test

---------ds_test--------------


<xarray.Dataset>
Dimensions:      (bnds: 2, hydro: 9, lat: 637, level: 150, lon: 589)
Coordinates:
  * lat          (lat) float64 47.5 47.51 47.52 47.53 ... 54.46 54.47 54.48 54.5
  * lon          (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
Dimensions without coordinates: bnds, hydro, level
Data variables:
    lat_bnds     (lat, bnds) float32 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    lon_bnds     (lon, bnds) float32 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    height       (level, lat, lon) float32 0.0 0.0 0.0 ... 2.081e+04 2.081e+04
    pfull        (level, lat, lon) float32 0.0 0.0 0.0 ... 4.946e+03 4.946e+03
    phalf        (level, lat, lon) float32 9.722e+04 9.718e+04 ... 5.087e+03
    T_abs        (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 218.8 218.9 218.9
    qv           (level, lat, lon) float32 0.0 0.0 0.0 ... 3.926e-06 3.925e-06
    rh           (level, lat, lon) float32 0.0 0.0 0.0 ... 0.8159 0.8128 0.8116
    tca          (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    cca          (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    mr_lsliq     (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    mr_lsice     (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    mr_ccliq     (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    mr_ccice     (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    fl_lsrain    (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    fl_lssnow    (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    fl_lsgrpl    (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    fl_ccrain    (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    fl_ccsnow    (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    orography    (lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    landmask     (lat, lon) float32 nan nan nan nan nan ... 0.0 0.0 0.0 0.0 0.0
    height_half  (level, lat, lon) float32 0.0 0.0 0.0 ... 2.062e+04 2.062e+04
    psfc         (lat, lon) float32 9.722e+04 9.718e+04 ... 1.026e+05 1.026e+05
    Reff         (hydro, level, lat, lon) float32 0.0 0.0 0.0 ... 0.0 0.0 0.0
    dtau_s       (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    dtau_c       (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    dem_s        (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    dem_c        (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    skt          (lat, lon) float32 292.2 292.0 292.1 ... 279.3 279.3 279.3
    sunlit       (lat, lon) float32 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0
    emsfc_lw     float32 0.99
    mr_ozone     (level, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    u_wind       (lat, lon) float32 0.0 0.0 0.0 0.0 ... -1.782 -2.541 -3.036
    v_wind       (lat, lon) float32 0.0 0.0 0.0 0.0 ... -4.77 -4.83 -4.738
    lwp          (lat, lon) float32 nan nan nan nan ... 0.02618 0.001904 0.0
    iwp          (lat, lon) float32 nan nan nan ... 9.761e-05 8.929e-05

In [49]:
print('---------ds_mydata--------------')
ds_mydata

---------ds_mydata--------------


<xarray.Dataset>
Dimensions:       (bnds: 2, height: 150, lat: 637, lon: 589)
Coordinates:
  * lon           (lon) float64 4.5 4.517 4.534 4.551 ... 14.45 14.46 14.48 14.5
  * lat           (lat) float64 47.5 47.51 47.52 47.53 ... 54.47 54.48 54.5
  * height        (height) float64 1.0 2.0 3.0 4.0 ... 147.0 148.0 149.0 150.0
Dimensions without coordinates: bnds
Data variables:
    height_bnds   (height, bnds) float64 1.0 2.0 2.0 3.0 ... 150.0 150.0 151.0
    hus           (height, lat, lon) float32 0.0 0.0 0.0 ... 0.004595 0.004553
    clw           (height, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    cli           (height, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    qr            (height, lat, lon) float32 0.0 0.0 0.0 ... 3.798e-18 2.872e-20
    qs            (height, lat, lon) float32 0.0 0.0 0.0 ... 1.016e-39 1.528e-39
    ta            (height, lat, lon) float32 0.0 0.0 0.0 ... 279.5 279.5 279.4
    pres          (height, lat, lon) float32 0.0 0.0 0.0 ... 1.025e+05 1.025e+05
    clc           (height, lat, lon) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    ps            (lat, lon) float32 9.717e+04 9.716e+04 ... 1.026e+05 1.026e+05
    u_10m         (lat, lon) float32 -2.077 -1.94 -1.94 ... -1.896 -1.852 -1.8
    v_10m         (lat, lon) float32 -2.399 -2.418 -2.418 ... -4.847 -4.88
    t_s           (lat, lon) float32 291.3 291.3 291.3 ... 279.3 279.3 279.3
    FR_LAND       (lat, lon) float32 1.0 1.0 1.0 1.0 1.0 ... 0.0 0.0 0.0 0.0 0.0
    Z_ifc         (height, lat, lon) float32 2.062e+04 2.062e+04 ... 0.0 0.0
    Z_mc          (height, lat, lon) float32 2.081e+04 2.081e+04 ... 10.0 10.0
    Topography_c  (lat, lon) float32 411.2 411.7 411.7 393.6 ... 0.0 0.0 0.0 0.0
Attributes:
    CDI:          Climate Data Interface version 1.9.10 (https://mpimet.mpg.d...
    Conventions:  CF-1.4
    uuidOfVGrid:  3be5ac35-92f4-4e91-7418-b62336222e20
    title:        ICON simulation
    history:      Wed Apr 21 18:39:25 2021: cdo -O -f nc merge 3D.nc 2D_vf.nc...
    references:   see MPIM/DWD publications
    comment:      HDCP2 Sammelaccount (k203095) on m21744 (Linux 2.6.32-696.1...
    NCO:          netCDF Operators version 4.9.3 (Homepage = http://nco.sf.ne...
    CDO:          Climate Data Operators version 1.9.10 (https://mpimet.mpg.d...

In [53]:
ds_test['level'].values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [54]:
height =ds_test['height']
print('-----------------------')
print(height.shape, height[:,:,:].values) #,tca.values)
#print(height.shape, height[:,149,149].values) #,tca.values)
print('-----------------------')

Z_mc =ds_mydata['Z_mc']
print('-----------------------')
print(Z_mc.shape,Z_mc[:,:,:].values)



-----------------------
(150, 637, 589) [[[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  ...
  [1.0000000e+01 1.0000000e+01 1.0000000e+01 ... 1.0000000e+01
   1.0000000e+01 1.0000000e+01]
  [1.0000000e+01 1.0000000e+01 1.0000000e+01 ... 1.0000000e+01
   1.0000000e+01 1.0000000e+01]
  [1.0000000e+01 1.0000000e+01 1.0000000e+01 ... 1.0000000e+01
   1.0000000e+01 1.0000000e+01]]

 [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
   0.0000000e+00 0.0000000e+00]
  ...
  [3.4776939e+01 3.4776939e+01 3.4776939e+01 ... 3.4776939e+01
   3.4776939e+01 3.4776939e+

In [52]:
import numpy as np
tca =ds_test['tca']
print('-----------------------')
print(tca.shape) #,tca.values)

uniqueValues, occurCount = np.unique(tca, return_counts=True)
print("Unique Values: " , uniqueValues)
print("Occurrence Count : ", occurCount)

clc =ds_mydata['clc']
print('-----------------------')
print(clc.shape)
uniqueValues, occurCount = np.unique(clc, return_counts=True)
print("Unique Values: " , uniqueValues)
print("Occurrence Count : ", occurCount)

-----------------------
(150, 637, 589)
Unique Values:  [0.0000000e+00 3.7793197e-07 8.2865915e-07 ... 9.9999803e-01 9.9999863e-01
 1.0000000e+00]
Occurrence Count :  [50990886        2        1 ...        1        1  4541716]
-----------------------
(150, 637, 589)
Unique Values:  [0.0000000e+00 1.1657470e-05 1.6833079e-05 ... 9.9999969e+01 9.9999977e+01
 1.0000000e+02]
Occurrence Count :  [46952692        1        1 ...        1        1  2197703]


In [10]:
np.shape(uniqueValues)

(4063735,)

In [11]:
height_half =ds_test['height_half']
print('-----------------------')
print(height_half.shape) #,tca.values)

uniqueValues, occurCount = np.unique(height_half, return_counts=True)
print("Unique Values: " , uniqueValues)
print("Occurrence Count : ", occurCount)


Z_ifc =ds_mydata['Z_ifc']
print('-----------------------')
print(Z_ifc.shape)
uniqueValues, occurCount = np.unique(Z_ifc, return_counts=True)
print("Unique Values: " , uniqueValues)
print("Occurrence Count : ", occurCount)

-----------------------
(150, 637, 589)
Unique Values:  [0.0000000e+00 9.7097958e-21 1.0477367e-19 ... 1.9982348e+04 2.0290234e+04
 2.0617793e+04]
Occurrence Count :  [826853      1      1 ... 369892 369892 369892]
-----------------------
(150, 637, 589)
Unique Values:  [ -137.1074   -116.8298   -111.97688 ... 19982.348   20290.234
 20617.793  ]
Occurrence Count :  [     1      1      1 ... 375193 375193 375193]


In [12]:
pfull =ds_test['pfull']
print('-----------------------') #pres disminuye con altura/ 0 level =0.mayor 149=top atmosphere menor 
print(pfull.shape, pfull[:,10,149].values)

pres =ds_mydata['pres']
print('-----------------------') #pres disminuye con altura/ 0 height =top atmos.menor 149=almost surface  mayor 
print(pres.shape, pres[:,10,149].values)


-----------------------
(150, 637, 589) [97689.22   97413.734  97062.95   96661.234  96223.18   95755.12
 95261.3    94745.016  94208.836  93654.76   93084.4    92499.39
 91901.125  91290.27   90667.734  90034.17   89389.836  88735.41
 88071.42   87398.26   86716.58   86026.81   85329.24   84624.06
 83912.16   83193.68   82468.914  81738.586  81002.51   80260.65
 79513.18   78760.56   78003.055  77240.53   76473.22   75701.33
 74925.48   74146.13   73363.1    72576.484  71786.39   70992.89
 70196.17   69396.44   68593.82   67788.914  66982.49   66174.85
 65366.297  64557.09   63747.33   62936.965  62126.     61314.316
 60501.777  59688.57   58874.93   58060.98   57246.89   56432.855
 55619.09   54805.844  53993.4    53182.098  52372.293  51564.17
 50758.105  49954.297  49152.75   48354.016  47558.496  46766.13
 45976.844  45190.71   44407.836  43628.28   42852.14   42079.516
 41310.582  40545.582  39784.754  39028.273  38276.29   37528.996
 36786.63   36049.402  35317.453  34590.85   3

In [13]:
#print(height_half.shape, height_half[:,149,149].values) #,tca.values)
#print('-----------------------')
#print(Z_ifc.shape,Z_ifc[:,149,149].values)
T_abs =ds_test['T_abs']
print('-----------------------') #temp disminuye con altura?? en topo 
print(T_abs[:,10,149].values)

ta =ds_mydata['ta']
print('-----------------------') #pres aumenta con altura
print( ta[:,10,149].values)


-----------------------
[287.5168  286.94357 286.4861  286.02682 285.5726  285.1221  284.68002
 284.56628 284.3396  284.23422 284.00726 284.18134 284.19113 284.004
 284.00308 283.73297 283.36642 283.16895 282.75125 282.41916 282.16223
 281.8075  281.41125 280.90463 280.95578 280.29202 280.25928 279.96048
 279.55453 279.02222 278.61505 278.2071  277.64725 276.87292 276.24255
 275.43884 275.0871  274.47226 273.8391  273.12933 272.35248 271.51956
 270.70493 269.86844 268.96884 268.42728 267.918   267.42017 266.9597
 266.48953 265.93362 265.26846 264.5512  263.65857 262.71173 261.7964
 260.8623  259.90433 258.9412  257.97577 257.01944 256.0783  255.16833
 254.31934 253.50717 252.6463  251.94928 251.08942 250.25763 249.61368
 248.92381 248.12285 247.26654 246.38382 245.47397 244.51633 243.54137
 242.53375 241.54352 240.57445 239.61784 238.6434  237.67139 236.71227
 235.77916 234.85603 233.9044  232.92682 231.90677 230.88246 229.9403
 229.0049  228.0288  226.9617  225.82666 224.67216 223.501

In [14]:
tca =ds_test['tca']
print('-----------------------') #temp disminuye con altura?? en topo 
print(tca[:,10,149].values)

clc =ds_mydata['clc']
print('-----------------------') #pres aumenta con altura
print( clc[:,10,149].values)


-----------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
-----------------------
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0

In [15]:
mr_lsliq =ds_test['mr_lsliq']
print('-----------------------') #temp disminuye con altura?? en topo 
print(mr_lsliq[:,149,149].values)

clw =ds_mydata['clw']
print('-----------------------') #pres aumenta con altura
print( clw[:,149,149].values)


-----------------------
[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 2.3268192e-06 6.1532461e-05
 2.0577306e-04 1.7295059e-04 1.0306269e-04 1.3201537e-04 7.3619904e-06
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e

In [16]:
mr_lsice =ds_test['mr_lsice']
print('-----------------------') #temp disminuye con altura?? en topo 
print(mr_lsice[:,149,149].values)

cli =ds_mydata['cli']
print('-----------------------') #pres aumenta con altura
print( cli[:,149,149].values)



-----------------------
[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 5.9869954e-08 7.2320205e-08 1.0500688e-07 1.1089275e-07 1.0905980e-07
 3.7291695e-08 1.7067565e-08 5.7033919e-08 2.7758681e-08 2.2023444e-08
 1.1192195e-08 1.8059723e-08 3.6721747e-08 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e

In [17]:
fl_lssnow =ds_test['fl_lssnow']
print('-----------------------') #temp disminuye con altura?? en topo 
print(fl_lssnow[:,149,149].values)

qs =ds_mydata['qs']
print('-----------------------') #pres aumenta con altura
print( qs[:,149,149].values)

-----------------------
[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 3.05652712e-08 3.17888897e-08 4.88222582e-08
 8.44936707e-08 1.09070221e-07 1.09999682e-07 1.11438908e-07
 1.11855755e-07 1.12670399e-07 9.97209284e-08 1.15226875e-07
 5.89901603e-08 4.49189663e-08 1.83023090e-08 2.22151275e-08
 2.59778066e-08 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00


In [18]:
orography =ds_test['orography']
print('-----------------------') #temp disminuye con altura?? en topo 
print(orography[:,149].values)

Topography_c =ds_mydata['Topography_c']
print('-----------------------') #pres aumenta con altura
print( Topography_c[:,149].values)

-----------------------
[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 3.76677887e+02 3.55325348e+02 3.46825378e+02
 3.50469452e+02 3.67217407e+02 3.70884827e+02 3.81126801e+02
 3.75196533e+02 3.99837433e+02 4.17999420e+02 3.97504395e+02
 3.99045685e+02 4.17293823e+02 3.93846985e+02 4.01739197e+02
 4.01302917e+02 6.14906677e+02 5.54376587e+02 5.59511841e+02
 7.86258545e+02 1.03556030e+03 8.40338318e+02 7.30905457e+02
 4.56651306e+02 4.40291626e+02 4.19431335e+02 5.68735840e+02
 8.76316162e+02 6.74998474e+02 1.06540894e+03 1.10953223e+03
 1.16215332e+03 1.25408069e+03 1.13587512e+03 1.06711731e+03
 1.00918793e+03 8.56338257e+02 5.89615234e+02 5.91918579e+02
 1.10585693e+03 1.10018140e+03 9.59752319e+02 9.05523682e+02
 1.17317163e+03 1.15413379e+03 1.04182202e+03 7.57902100e+02
 8.49843201e+02 7.52735718e+02 8.03898376e+02 9.64737732e+02
 7.62427856e+02 6.51239136e+02 7.28592224e+02 7.54796143e+02


In [19]:
'''   ok ps
psfc =ds_test['psfc']
print('-----------------------') #temp disminuye con altura?? en topo 
print(psfc[:,149].values)

ps =ds_mydata['ps']
print('-----------------------') #pres aumenta con altura
print( ps[:,149].values)
'''

"   ok ps\npsfc =ds_test['psfc']\nprint('-----------------------') #temp disminuye con altura?? en topo \nprint(psfc[:,149].values)\n\nps =ds_mydata['ps']\nprint('-----------------------') #pres aumenta con altura\nprint( ps[:,149].values)\n"

In [20]:
skt =ds_test['skt']
print('-----------------------') 
print(skt[:,:].values)

t_s =ds_mydata['t_s']
print('-----------------------') 
print( t_s[:,:].values)

-----------------------
[[292.18933 292.00922 292.07425 ... 294.3323  292.68417 292.73734]
 [292.18942 292.00916 292.07425 ... 294.33246 292.68423 292.73727]
 [292.18958 292.00906 292.07428 ... 294.3328  292.68433 292.73718]
 ...
 [280.05014 280.03494 280.01862 ... 279.38263 279.3708  279.358  ]
 [280.05124 280.03638 280.02008 ... 279.35205 279.33704 279.3258 ]
 [280.05295 280.0397  280.0212  ... 279.32068 279.3074  279.29266]]
-----------------------
[[291.33838 291.25867 291.25867 ... 290.71347 290.71347 290.71347]
 [291.33838 291.25867 291.25867 ... 290.71347 290.71347 290.71347]
 [291.5968  291.25867 291.25867 ... 290.71347 290.71347 290.71347]
 ...
 [280.04977 280.0353  280.01935 ... 279.38358 279.3709  279.35608]
 [280.05167 280.03525 280.01907 ... 279.3541  279.33652 279.32388]
 [280.05313 280.03992 280.02182 ... 279.31967 279.3074  279.29285]]


In [24]:
u_wind =ds_test['u_wind']
print('-----------------------') 
print(u_wind[:,:].values)

u_10m =ds_mydata['u_10m']
print('-----------------------') 
print( u_10m[:,:].values)

-----------------------
[[ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 ...
 [-5.3440857 -5.0319724 -5.1057124 ... -2.0774806 -2.8136275 -3.0489542]
 [-6.366407  -4.9486756 -5.0371757 ... -1.7631298 -2.637974  -3.1739786]
 [-7.0180674 -4.8791943 -5.0213037 ... -1.7822113 -2.5405986 -3.0362606]]
-----------------------
[[-2.077391  -1.940408  -1.940408  ... -1.3141216 -1.3141216 -1.3141216]
 [-2.077391  -1.940408  -1.940408  ... -1.3141216 -1.3141216 -1.3141216]
 [-1.9620287 -1.940408  -1.940408  ... -1.3141216 -1.3141216 -1.3141216]
 ...
 [-4.5632286 -4.548379  -4.480455  ... -1.8947028 -2.0149698 -2.09925  ]
 [-4.690715  -4.637089  -4.531679  ... -1.834213  -1.8451722 -1.9230292]
 [-4.7691975 -4.746933  -4.6280203 ... -1.8959658 -1.8518851 -1.8003418]]


In [32]:
v_wind =ds_test['v_wind']
print('-----------------------') 
print(v_wind[:,:].values)

v_10m =ds_mydata['v_10m']
print('-----------------------') 
print( v_10m[:,:].values)

-----------------------
[[ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 [ 0.         0.         0.        ...  0.         0.         0.       ]
 ...
 [-2.9993536 -2.984419  -3.0655916 ... -5.0725193 -4.8549695 -4.974335 ]
 [-3.343858  -3.1084309 -3.2005541 ... -4.877505  -4.73067   -4.7404094]
 [-1.9885541 -3.2069373 -3.2309732 ... -4.769542  -4.8302684 -4.7382345]]
-----------------------
[[-2.3987029  -2.4180684  -2.4180684  ... -0.08787012 -0.08787012
  -0.08787012]
 [-2.3987029  -2.4180684  -2.4180684  ... -0.08787012 -0.08787012
  -0.08787012]
 [-2.3585987  -2.4180684  -2.4180684  ... -0.08787012 -0.08787012
  -0.08787012]
 ...
 [-3.0429826  -3.110859   -3.205697   ... -5.149588   -4.9355946
  -4.760139  ]
 [-3.134193   -3.1626992  -3.2174644  ... -5.0350547  -5.003278
  -4.9112043 ]
 [-3.1427963  -3.1761045  -3.1965494  ... -4.8206077  -4.847248
  -4.879536  ]]


In [ ]:
fl_lsrain =ds_test['fl_lsrain']
print('-----------------------') #temp disminuye con altura?? en topo 
print(fl_lsrain[0,149,149].values)

qr =ds_mydata['qr']
print('-----------------------') #pres aumenta con altura
print( qr[149,149,149].values)



In [110]:
#### continuarrr con el codigo y u_10m

-----------------------
1.7032211e-05
-----------------------
3.9339542e-05


In [80]:
#print(height_half.shape, height_half[149,15,:].values) #,tca.values)
#print('-----------------------')
#print(Z_ifc.shape,Z_ifc[0,15,:].values)


In [70]:
#print(height.shape, height[:,149,149].values) #,tca.values)
#print(Z_mc.shape,Z_mc[:,149,149].values)


In [69]:
#print(Z_mc.shape, np.flip(Z_mc,0)[:,149,149].values)

In [ ]:
### REEMPLAZAR EN EL INPUT
Z_ifc=np.flip(Z_ifc,0)
Z_mc=np.flip(Z_mc,0)
pres=np.flip(pres,0)
ta=np.flip(ta,0)
hus=np.flip(hus,0)
clc[:]=clc/100
t_s[:]=t_s/100

In [66]:
print(height_half.shape, height_half[:,149,149].values) #,tca.values)
print(Z_ifc.shape, np.flip(Z_ifc,0)[:,149,149].values)


(150, 637, 589) [  267.92096   287.92096   316.09354   349.627     386.82645   427.04208
   469.86368   515.00635   562.25977   611.4622    662.4854    715.2252
   769.5955    825.5242    882.94995   941.8204   1002.09015  1063.7198
  1126.6752   1190.9258   1256.4451   1323.2094   1391.1979   1460.3921
  1530.7753   1602.333    1675.0521   1748.9208   1823.9288   1900.0669
  1977.3269   2055.7014   2135.1843   2215.7698   2297.453    2380.2295
  2464.096    2549.0488   2635.0857   2722.2046   2810.4033   2899.6812
  2990.0366   3081.4692   3173.979    3267.5657   3362.2295   3457.9714
  3554.792    3652.6926   3751.6743   3851.7388   3952.888    4055.1235
  4158.4478   4262.8633   4368.373    4474.979    4582.6846   4691.4927
  4801.407    4912.431    5024.569    5137.8237   5252.1997   5367.7017
  5484.334    5602.1006   5721.0073   5841.059    5962.2607   6084.6177
  6208.136    6332.8223   6458.681    6585.72     6713.946    6843.3647
  6973.984    7105.811    7238.854    7373.12  

-----------------------
(150, 637, 589) [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
-----------------------
(150, 637, 589) [20808.896   20454.014   20136.291   19834.89    19544.914   19263.902
 18990.357   18723.26    18461.871   18205.63    17954.094   17706.9
 17463.752   17224.395   16988.615   16756.223   16527.057   16300.97
 16078.878   15859.717   15642.34    15427.607   15215.433   15005.736
 14798.443   14593.487   14390.804   14190.335   13992.025   13795.824
 13601.684   13409.559   13219.405   13031.186   12844.86    12660.395
 12477.755   12296.908   12117.824   11